# Site settings
title: Sérgio Miguel Fernandes' homepage
email: s@sfernandes.net
description: > # this means to ignore newlines until "baseurl:"
# Hi there!
baseurl: "" # the subpath of your site, e.g. /blog (no trailling slash)
url: "http://www.sfernandes.net" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  smmf

# Build settings
markdown: kramdown
safe: true
